### ISSUE TITLE
Move to Page Top : When selected learning cards from list at bottom the page does not scroll.

### ISSUE THREAD

**Issue by RajeevMK** [LIOSK-ORG/learningCards-app#30]
How to reproduce.
1. Select Learning Cards list
2. Scroll down to bottom
3. Select LearningCard to view
4. Learning Card View page displays but does not show the top page.. we need to scroll to top to view.

Every new learning cards should scroll to top.

**Comment by Rahman-S-M** [comment]
Fixed at the top of the router. 

Solution Used :

https://nicolasforgerit.com/2016/04/27/angular2-automatic-scroll-to-top/
