### ISSUE TITLE
Starting of the learning cards - with start button

### ISSUE THREAD

**Issue by Jyothipamala** [LIOSK-ORG/learningCards-app#4]
Instead of directly showing the cards, it would be good to show a start button to start the slides/cards.

**Comment by Rahman-S-M** [comment]
Its like starting and ending pages. When we click , we already started the learning/practice. I don't think we need that for learning. But need to change this for practice and quiz.

**Comment by Rahman-S-M** [comment]
No need to have multiple buttons to start the learning cards. Adding another page to start doesn't seem good.
